/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................coverageLib.CoverageInstrumentation
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "coverageLib_CoverageInstrumentation_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/
/*method "markBinaryBranchExecuted" not generated due to Implementation option "Generate method body" turned off */
/*method "markBranchExecuted" not generated due to Implementation option "Generate method body" turned off */
/*method "markStatementExecuted" not generated due to Implementation option "Generate method body" turned off */
/*method "trackCondition" not generated due to Implementation option "Generate method body" turned off */
/*method "trackDecision" not generated due to Implementation option "Generate method body" turned off */

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



