/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................coverageLib.CoverageInstrumentation
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_COVERAGELIB_COVERAGEINSTRUMENTATION_AUTOMATIC_H_
#define _ASD_COVERAGELIB_COVERAGEINSTRUMENTATION_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "esdl_coverage.h"
#include "chartab.h"


/* component structure for class COVERAGELIB_COVERAGEINSTRUMENTATION_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: coverageLib_CoverageInstrumentation_Automatic */
#define _coverageLib_CoverageInstrumentation_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class coverageLib_CoverageInstrumentation_Automatic
 ******************************************************************************/
#if !defined(SUPPRESS_SRV_FUNCTION_DECLARATION) && !defined(coverageLib_CoverageInstrumentation_Automatic_SUPPRESS_FUNCTION_DECLARATION)
extern boolean _cov_binary_branch_ (
   /* IN    */ const uint32  instrumentationId,
   /* IN    */ const boolean value
   );
extern void _cov_branch_ (
   /* IN    */ const uint32 instrumentationId,
   /* IN    */ const uint32 index
   );
extern boolean _cov_condition_ (
   /* IN    */ const uint32  decisionId,
   /* IN    */ const uint32  conditionId,
   /* IN    */ const boolean value
   );
extern boolean _cov_decision_ (
   /* IN    */ const uint32  instrumentationId,
   /* IN    */ const uint32  conditionNumber,
   /* IN    */ const boolean value
   );
extern void _cov_statement_ (/* IN    */ const uint32 instrumentationId);
#endif



#endif /* _ASD_COVERAGELIB_COVERAGEINSTRUMENTATION_AUTOMATIC_H_ */
