/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................driver.DrivingSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "driver_DrivingSM_Automatic.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/




/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define ACCState 0U
#define BrakeState 1U



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_drivingSMStatemachineTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'drivingSMStatemachineTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void driver_DrivingSM_Automatic_drivingSMStatemachineTrigger ( const struct driver_DrivingSM_Automatic * self)
{
   switch (self->driver_DrivingSM_Automatic_RAM->sm)
   {
      case BrakeState:
         if (_cov_binary_branch_(8U, self->driver_DrivingSM_Automatic_RAM->green))
         {
            _cov_statement_(210U);
            self->driver_DrivingSM_Automatic_RAM->sm = ACCState;
            break;
         } /* end if */
         _cov_statement_(209U);
         self->driver_DrivingSM_Automatic_RAM->cruising = false;
         break;
      case ACCState:
      default:
         if (_cov_binary_branch_(7U, (40.0F <= self->driver_DrivingSM_Automatic_RAM->proximity) && (self->driver_DrivingSM_Automatic_RAM->proximity <= 100.0F) && (!self->driver_DrivingSM_Automatic_RAM->green)))
         {
            _cov_statement_(210U);
            _cov_statement_(211U);
            self->driver_DrivingSM_Automatic_RAM->sm = BrakeState;
            break;
         } /* end if */
         _cov_statement_(210U);
         _cov_statement_(208U);
         self->driver_DrivingSM_Automatic_RAM->cruising = true;
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_drivingSMStatemachineTrigger'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_esdl_getState'
 * ----------------------------------------------------------------------------
 * model name:...................................'esdl_getState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 driver_DrivingSM_Automatic_esdl_getState ( const struct driver_DrivingSM_Automatic * self)
{
   return self->driver_DrivingSM_Automatic_RAM->sm;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_esdl_getState'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



