/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLight
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "environment_TrafficLight_Automatic.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getGreen'
 * ----------------------------------------------------------------------------
 * model name:...................................'getGreen'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getGreen ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(82U);
   return self->environment_TrafficLight_Automatic_RAM->green;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getGreen'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 environment_TrafficLight_Automatic_getPosition ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(79U);
   return self->environment_TrafficLight_Automatic_RAM->position;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getProximity'
 * ----------------------------------------------------------------------------
 * model name:...................................'getProximity'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 environment_TrafficLight_Automatic_getProximity ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(75U);
   return self->environment_TrafficLight_Automatic_RAM->proximity;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getProximity'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getRed'
 * ----------------------------------------------------------------------------
 * model name:...................................'getRed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getRed ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(80U);
   return self->environment_TrafficLight_Automatic_RAM->red;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getRed'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getVisible'
 * ----------------------------------------------------------------------------
 * model name:...................................'getVisible'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getVisible ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(74U);
   return self->environment_TrafficLight_Automatic_RAM->isVisible;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getVisible'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getYellow'
 * ----------------------------------------------------------------------------
 * model name:...................................'getYellow'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getYellow ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(81U);
   return self->environment_TrafficLight_Automatic_RAM->yellow;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getYellow'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setGreen'
 * ----------------------------------------------------------------------------
 * model name:...................................'setGreen'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setGreen (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     g
   )
{
   _cov_statement_(73U);
   self->environment_TrafficLight_Automatic_RAM->green = g;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setGreen'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'setPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setPosition (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const float32                                     pos
   )
{
   _cov_statement_(68U);
   self->environment_TrafficLight_Automatic_RAM->position = pos;
   _cov_statement_(69U);
   self->environment_TrafficLight_Automatic_RAM->proximity = pos;
   _cov_statement_(70U);
   environment_TrafficLight_Automatic_updateVisibility(self);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setRed'
 * ----------------------------------------------------------------------------
 * model name:...................................'setRed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setRed (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     r
   )
{
   _cov_statement_(71U);
   self->environment_TrafficLight_Automatic_RAM->red = r;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setRed'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setYellow'
 * ----------------------------------------------------------------------------
 * model name:...................................'setYellow'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setYellow (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     y
   )
{
   _cov_statement_(72U);
   self->environment_TrafficLight_Automatic_RAM->yellow = y;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setYellow'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateProximity'
 * ----------------------------------------------------------------------------
 * model name:...................................'updateProximity'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_updateProximity (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const float32                                     carElapsed
   )
{
   _cov_statement_(77U);
   self->environment_TrafficLight_Automatic_RAM->proximity
      = self->environment_TrafficLight_Automatic_RAM->position - carElapsed;
   _cov_statement_(78U);
   environment_TrafficLight_Automatic_updateVisibility(self);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateProximity'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateVisibility'
 * ----------------------------------------------------------------------------
 * model name:...................................'updateVisibility'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_updateVisibility ( const struct environment_TrafficLight_Automatic * self)
{
   _cov_statement_(76U);
   self->environment_TrafficLight_Automatic_RAM->isVisible
      = (self->environment_TrafficLight_Automatic_RAM->proximity >= 0.0F)
      && (self->environment_TrafficLight_Automatic_RAM->proximity <= 100.0F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateVisibility'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



