/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.LightSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_ENVIRONMENT_LIGHTSM_AUTOMATIC_H_
#define _ASD_ENVIRONMENT_LIGHTSM_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'environment_LightSM_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct environment_LightSM_Automatic_RAM_SUBSTRUCT {
   float32 elapsedTime;
   boolean green;
   boolean red;
   uint8 sm;
   boolean yellow;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'environment_LightSM_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'environment_LightSM_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct environment_LightSM_Automatic {
   struct environment_LightSM_Automatic_RAM_SUBSTRUCT * environment_LightSM_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'environment_LightSM_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............environment_LightSM_Automatic */
#define _environment_LightSM_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class environment_LightSM_Automatic
 ******************************************************************************/
uint8 environment_LightSM_Automatic_esdl_getState ( const struct environment_LightSM_Automatic * self);
extern void environment_LightSM_Automatic_trafficLightSMStatemachineTrigger ( const struct environment_LightSM_Automatic * self);



#endif /* _ASD_ENVIRONMENT_LIGHTSM_AUTOMATIC_H_ */
