/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................StopRollGo
 * REPRESENTATION:..............
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_STOPROLLGO_AUTOMATIC_H_
#define _ASD_STOPROLLGO_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "environment_FlashLight_Automatic.h"
#include "UnitTests_UnitTest_driver_Automatic.h"
#include "UnitTests_UnitTest_DrivingSM_Automatic.h"
#include "UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic.h"
#include "UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic.h"
#include "UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic.h"
#include "UnitTests_UnitTest_FlashLight_Automatic.h"
#include "UnitTests_UnitTest_Light_Automatic.h"
#include "UnitTests_UnitTest_LightSM_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_testGreen_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_testInvisiblePosition_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_testRed_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_testUpdateProximity_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic.h"
#include "UnitTests_UnitTest_TrafficLight_testYellow_Automatic.h"


/* component structure for project STOPROLLGO_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .......................StopRollGo_Automatic */
#define _StopRollGo_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project StopRollGo_Automatic
 ******************************************************************************/





#endif /* _ASD_STOPROLLGO_AUTOMATIC_H_ */
