/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_TrafficLight_testVisiblePosition
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_TrafficLight_testVisiblePosition'
 * data set:.....................................'UNITTESTS_UNITTEST_TRAFFICLIGHT_TESTVISIBLEPOSITION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM = {
   /* substruct: UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance (modeled as:'TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
   {
      /* struct element:'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance.position' (modeled as:'position.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance.proximity' (modeled as:'proximity.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance.green' (modeled as:'green.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance.isVisible' (modeled as:'isVisible.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance.red' (modeled as:'red.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance.yellow' (modeled as:'yellow.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_TrafficLight_testVisiblePosition'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_TrafficLight_testVisiblePosition'
 * data set:.....................................'UNITTESTS_UNITTEST_TRAFFICLIGHT_TESTVISIBLEPOSITION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic UnitTests_UnitTest_TrafficLight_testVisiblePosition = {
   /* substruct: UnitTests_UnitTest_TrafficLight_testVisiblePosition.TrafficLight_testInstance (modeled as:'TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testVisiblePosition') */
   {
      /* type descriptor pointer 'environment_TrafficLight_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_TrafficLight_testVisiblePosition_RAM.TrafficLight_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_TrafficLight_testVisiblePosition'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic_testVisiblePosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'testVisiblePosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic_testVisiblePosition (void)
{
   _cov_statement_(41U);
   environment_TrafficLight_Automatic_setPosition(&(UnitTests_UnitTest_TrafficLight_testVisiblePosition.TrafficLight_testInstance), 50.0F);
   _cov_statement_(42U);
   ASSERT_NEAR(50.0, (float64)environment_TrafficLight_Automatic_getProximity(&(UnitTests_UnitTest_TrafficLight_testVisiblePosition.TrafficLight_testInstance)), 0.001);
   _cov_statement_(43U);
   ASSERT_NEAR(50.0, (float64)environment_TrafficLight_Automatic_getPosition(&(UnitTests_UnitTest_TrafficLight_testVisiblePosition.TrafficLight_testInstance)), 0.001);
   _cov_statement_(44U);
   ASSERT_TRUE(environment_TrafficLight_Automatic_getVisible(&(UnitTests_UnitTest_TrafficLight_testVisiblePosition.TrafficLight_testInstance)));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_TrafficLight_testVisiblePosition_Automatic_testVisiblePosition'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



