/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_TrafficLight
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_TrafficLight_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_TrafficLight_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_TrafficLight'
 * data set:.....................................'UNITTESTS_UNITTEST_TRAFFICLIGHT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_TrafficLight_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_TrafficLight_RAM = {
   /* substruct: UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance (modeled as:'TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
   {
      /* struct element:'UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance.position' (modeled as:'position.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance.proximity' (modeled as:'proximity.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance.green' (modeled as:'green.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance.isVisible' (modeled as:'isVisible.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance.red' (modeled as:'red.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance.yellow' (modeled as:'yellow.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_TrafficLight_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_TrafficLight'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_TrafficLight'
 * data set:.....................................'UNITTESTS_UNITTEST_TRAFFICLIGHT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_TrafficLight_Automatic UnitTests_UnitTest_TrafficLight = {
   /* substruct: UnitTests_UnitTest_TrafficLight.TrafficLight_testInstance (modeled as:'TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight') */
   {
      /* type descriptor pointer 'environment_TrafficLight_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_TrafficLight_RAM.TrafficLight_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_TrafficLight'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



