/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_DrivingSM_testDrivingSMInvisible
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_TESTDRIVINGSMINVISIBLE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM = {
   /* substruct: UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible') */
   {
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.proximity' (modeled as:'proximity.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.cruising' (modeled as:'cruising.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible') */
      true,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.green' (modeled as:'green.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible') */
      false,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.sm' (modeled as:'sm.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_TESTDRIVINGSMINVISIBLE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible = {
   /* substruct: UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible') */
   {
      /* type descriptor pointer 'driver_DrivingSM_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic_testDrivingSMInvisible'
 * ----------------------------------------------------------------------------
 * model name:...................................'testDrivingSMInvisible'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic_testDrivingSMInvisible (void)
{
   /* user defined local variables */
   boolean testGreen;
   float32 testProximity;

   testProximity = 110.0F;
   testGreen = false;
   _cov_statement_(181U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.cruising);
   _cov_statement_(182U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.proximity = testProximity;
   _cov_statement_(183U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.green = testGreen;
   _cov_statement_(184U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible.DrivingSM_testInstance));
   _cov_statement_(185U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible.DrivingSM_testInstance));
   _cov_statement_(186U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.cruising);
   _cov_statement_(187U);
   testGreen = true;
   _cov_statement_(188U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.green = testGreen;
   _cov_statement_(189U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible.DrivingSM_testInstance));
   _cov_statement_(190U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible.DrivingSM_testInstance));
   _cov_statement_(191U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_RAM.DrivingSM_testInstance.cruising);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_DrivingSM_testDrivingSMInvisible_Automatic_testDrivingSMInvisible'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



