/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_driver_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"
#include "ESDL_Linear_Interpolation.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'UnitTests_UnitTest_driver'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_driver_Automatic_CAL_MEM_SUBSTRUCT UnitTests_UnitTest_driver_CAL_MEM = {
   /* struct element:'UnitTests_UnitTest_driver_CAL_MEM.InverseBrakeMomentum' (modeled as:'InverseBrakeMomentum.UnitTests_UnitTest_driver') */
   {
      5U,
      {
         -4.0F, -3.0F, -2.0F, -1.0F, 0.0F
      },
      {
         100.0F, 80.0F, 60.0F, 40.0F, 0.0F
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_driver_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_driver'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_driver_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_driver_RAM = {
   /* struct element:'UnitTests_UnitTest_driver_RAM.brake' (modeled as:'brake.UnitTests_UnitTest_driver') */
   0.0F,
   /* struct element:'UnitTests_UnitTest_driver_RAM.power' (modeled as:'power.UnitTests_UnitTest_driver') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_driver_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_driver'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_reset'
 * ----------------------------------------------------------------------------
 * model name:...................................'reset'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_driver_Automatic_reset (void)
{
   _cov_statement_(148U);
   UnitTests_UnitTest_driver_RAM.power = 0.0F;
   _cov_statement_(149U);
   UnitTests_UnitTest_driver_RAM.brake = 0.0F;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_reset'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testCalc'
 * ----------------------------------------------------------------------------
 * model name:...................................'testCalc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_driver_Automatic_testCalc (
   /* IN    */ const float32 v,
   /* IN    */ const float32 visibleProximity,
   /* IN    */ const boolean cruising
   )
{
   /* user defined local variables */
   float32 requiredBrakeMomentum;
   /* temp. variables */
   float32 _t1real32;
   float32 _t2real32;

   requiredBrakeMomentum = 0.0F;
   _cov_statement_(150U);
   _t1real32 = (visibleProximity + 8.0F) * -25.92F;
   _t2real32 = v * v;
   requiredBrakeMomentum
      = ESDL_Linear_CharTable1_getAt_r32r32(((&(UnitTests_UnitTest_driver_CAL_MEM.InverseBrakeMomentum)))->xSize, ((&(UnitTests_UnitTest_driver_CAL_MEM.InverseBrakeMomentum)))->xDist, ((&(UnitTests_UnitTest_driver_CAL_MEM.InverseBrakeMomentum)))->values, ((_t1real32 == 0.0F) ? _t2real32 : (_t2real32 / _t1real32)));
   _cov_statement_(151U);
   if (_cov_binary_branch_(1U, cruising))
   {
      _cov_statement_(152U);
      if (_cov_binary_branch_(2U, v >= 50.0F))
      {
         _cov_statement_(153U);
         UnitTests_UnitTest_driver_RAM.power = 0.0F;
         _cov_statement_(154U);
         UnitTests_UnitTest_driver_RAM.brake = 70.0F;
      }
      else
      {
         _cov_statement_(155U);
         UnitTests_UnitTest_driver_RAM.power = 100.0F;
         _cov_statement_(156U);
         UnitTests_UnitTest_driver_RAM.brake = 0.0F;
      } /* end if */
   }
   else
   {
      _cov_statement_(157U);
      UnitTests_UnitTest_driver_RAM.power = 0.0F;
      _cov_statement_(158U);
      UnitTests_UnitTest_driver_RAM.brake = requiredBrakeMomentum;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testCalc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testDriverCruising'
 * ----------------------------------------------------------------------------
 * model name:...................................'testDriverCruising'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_driver_Automatic_testDriverCruising (void)
{
   /* user defined local variables */
   boolean testCruising;
   float32 testProximity;
   float32 testV;

   testCruising = true;
   testProximity = 0.0F;
   testV = 30.0F;
   _cov_statement_(126U);
   UnitTests_UnitTest_driver_Automatic_reset();
   _cov_statement_(127U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 0.0, 0.001);
   _cov_statement_(128U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 0.0, 0.001);
   _cov_statement_(129U);
   UnitTests_UnitTest_driver_Automatic_testCalc(testV, testProximity, testCruising);
   _cov_statement_(130U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 100.0, 0.001);
   _cov_statement_(131U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 0.0, 0.001);
   _cov_statement_(132U);
   testV = 70.0F;
   _cov_statement_(133U);
   UnitTests_UnitTest_driver_Automatic_testCalc(testV, testProximity, testCruising);
   _cov_statement_(134U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 0.0, 0.001);
   _cov_statement_(135U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 70.0, 0.001);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testDriverCruising'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testDriverNotCruising'
 * ----------------------------------------------------------------------------
 * model name:...................................'testDriverNotCruising'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_driver_Automatic_testDriverNotCruising (void)
{
   /* user defined local variables */
   boolean testCruising;
   float32 testProximity;
   float32 testV;

   testCruising = false;
   testProximity = 70.0F;
   testV = 50.0F;
   _cov_statement_(136U);
   UnitTests_UnitTest_driver_Automatic_reset();
   _cov_statement_(137U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 0.0, 0.001);
   _cov_statement_(138U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 0.0, 0.001);
   _cov_statement_(139U);
   UnitTests_UnitTest_driver_Automatic_testCalc(testV, testProximity, testCruising);
   _cov_statement_(140U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 0.0, 0.001);
   _cov_statement_(141U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 45.0, 2.0);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testDriverNotCruising'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testDriverNotCruisingClose'
 * ----------------------------------------------------------------------------
 * model name:...................................'testDriverNotCruisingClose'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_driver_Automatic_testDriverNotCruisingClose (void)
{
   /* user defined local variables */
   boolean testCruising;
   float32 testProximity;
   float32 testV;

   testCruising = false;
   testProximity = 40.0F;
   testV = 50.0F;
   _cov_statement_(142U);
   UnitTests_UnitTest_driver_Automatic_reset();
   _cov_statement_(143U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 0.0, 0.001);
   _cov_statement_(144U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 0.0, 0.001);
   _cov_statement_(145U);
   UnitTests_UnitTest_driver_Automatic_testCalc(testV, testProximity, testCruising);
   _cov_statement_(146U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.power, 0.0, 0.001);
   _cov_statement_(147U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_driver_RAM.brake, 60.0, 2.0);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_driver_Automatic_testDriverNotCruisingClose'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



