/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_LightSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_LightSM_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_LightSM_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_LightSM'
 * data set:.....................................'UNITTESTS_UNITTEST_LIGHTSM_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_LightSM_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_LightSM_RAM = {
   /* substruct: UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance (modeled as:'LightSM_testInstance.UnitTests_UnitTest_LightSM') */
   {
      /* struct element:'UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.elapsedTime' (modeled as:'elapsedTime.LightSM_testInstance.UnitTests_UnitTest_LightSM') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green' (modeled as:'green.LightSM_testInstance.UnitTests_UnitTest_LightSM') */
      false,
      /* struct element:'UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red' (modeled as:'red.LightSM_testInstance.UnitTests_UnitTest_LightSM') */
      false,
      /* struct element:'UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.sm' (modeled as:'sm.LightSM_testInstance.UnitTests_UnitTest_LightSM') */
      0U,
      /* struct element:'UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow' (modeled as:'yellow.LightSM_testInstance.UnitTests_UnitTest_LightSM') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_LightSM_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_LightSM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_LightSM'
 * data set:.....................................'UNITTESTS_UNITTEST_LIGHTSM_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_LightSM_Automatic UnitTests_UnitTest_LightSM = {
   /* substruct: UnitTests_UnitTest_LightSM.LightSM_testInstance (modeled as:'LightSM_testInstance.UnitTests_UnitTest_LightSM') */
   {
      /* type descriptor pointer 'environment_LightSM_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_LightSM'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_LightSM_Automatic_testLightSM'
 * ----------------------------------------------------------------------------
 * model name:...................................'testLightSM'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_LightSM_Automatic_testLightSM (void)
{
   _cov_statement_(0U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(1U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(2U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
   _cov_statement_(3U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(4U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(5U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(6U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
   _cov_statement_(7U);
   UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.elapsedTime = 5.0F;
   _cov_statement_(8U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(9U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(10U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(11U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(12U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
   _cov_statement_(13U);
   UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.elapsedTime = 42.0F;
   _cov_statement_(14U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(15U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(16U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(17U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(18U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
   _cov_statement_(19U);
   UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.elapsedTime = 45.0F;
   _cov_statement_(20U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(21U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(22U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(23U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(24U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
   _cov_statement_(25U);
   UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.elapsedTime = 59.0F;
   _cov_statement_(26U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(27U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(28U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(29U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(30U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
   _cov_statement_(31U);
   UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.elapsedTime = 1.0F;
   _cov_statement_(32U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(33U);
   environment_LightSM_Automatic_trafficLightSMStatemachineTrigger(&(UnitTests_UnitTest_LightSM.LightSM_testInstance));
   _cov_statement_(34U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.red);
   _cov_statement_(35U);
   ASSERT_TRUE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.yellow);
   _cov_statement_(36U);
   ASSERT_FALSE(UnitTests_UnitTest_LightSM_RAM.LightSM_testInstance.green);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_LightSM_Automatic_testLightSM'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



