/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_TrafficLight_testYellow
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_TrafficLight_testYellow_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_TrafficLight_testYellow_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_TrafficLight_testYellow'
 * data set:.....................................'UNITTESTS_UNITTEST_TRAFFICLIGHT_TESTYELLOW_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_TrafficLight_testYellow_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_TrafficLight_testYellow_RAM = {
   /* substruct: UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance (modeled as:'TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
   {
      /* struct element:'UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance.position' (modeled as:'position.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance.proximity' (modeled as:'proximity.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance.green' (modeled as:'green.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance.isVisible' (modeled as:'isVisible.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance.red' (modeled as:'red.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
      false,
      /* struct element:'UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance.yellow' (modeled as:'yellow.TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_TrafficLight_testYellow_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_TrafficLight_testYellow'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_TrafficLight_testYellow'
 * data set:.....................................'UNITTESTS_UNITTEST_TRAFFICLIGHT_TESTYELLOW_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_TrafficLight_testYellow_Automatic UnitTests_UnitTest_TrafficLight_testYellow = {
   /* substruct: UnitTests_UnitTest_TrafficLight_testYellow.TrafficLight_testInstance (modeled as:'TrafficLight_testInstance.UnitTests_UnitTest_TrafficLight_testYellow') */
   {
      /* type descriptor pointer 'environment_TrafficLight_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_TrafficLight_testYellow_RAM.TrafficLight_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_TrafficLight_testYellow'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_TrafficLight_testYellow_Automatic_testYellow'
 * ----------------------------------------------------------------------------
 * model name:...................................'testYellow'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_TrafficLight_testYellow_Automatic_testYellow (void)
{
   _cov_statement_(63U);
   ASSERT_FALSE(environment_TrafficLight_Automatic_getYellow(&(UnitTests_UnitTest_TrafficLight_testYellow.TrafficLight_testInstance)));
   _cov_statement_(64U);
   environment_TrafficLight_Automatic_setYellow(&(UnitTests_UnitTest_TrafficLight_testYellow.TrafficLight_testInstance), true);
   _cov_statement_(65U);
   ASSERT_TRUE(environment_TrafficLight_Automatic_getYellow(&(UnitTests_UnitTest_TrafficLight_testYellow.TrafficLight_testInstance)));
   _cov_statement_(66U);
   environment_TrafficLight_Automatic_setYellow(&(UnitTests_UnitTest_TrafficLight_testYellow.TrafficLight_testInstance), false);
   _cov_statement_(67U);
   ASSERT_FALSE(environment_TrafficLight_Automatic_getYellow(&(UnitTests_UnitTest_TrafficLight_testYellow.TrafficLight_testInstance)));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_TrafficLight_testYellow_Automatic_testYellow'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



