/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_DrivingSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_DrivingSM_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_DrivingSM_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_DrivingSM_RAM = {
   /* substruct: UnitTests_UnitTest_DrivingSM_RAM.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM') */
   {
      /* struct element:'UnitTests_UnitTest_DrivingSM_RAM.DrivingSM_testInstance.proximity' (modeled as:'proximity.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_DrivingSM_RAM.DrivingSM_testInstance.cruising' (modeled as:'cruising.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM') */
      true,
      /* struct element:'UnitTests_UnitTest_DrivingSM_RAM.DrivingSM_testInstance.green' (modeled as:'green.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM') */
      false,
      /* struct element:'UnitTests_UnitTest_DrivingSM_RAM.DrivingSM_testInstance.sm' (modeled as:'sm.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_DrivingSM_Automatic UnitTests_UnitTest_DrivingSM = {
   /* substruct: UnitTests_UnitTest_DrivingSM.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM') */
   {
      /* type descriptor pointer 'driver_DrivingSM_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_DrivingSM_RAM.DrivingSM_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



