/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_DrivingSM_testDrivingSMVisibleLess40
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_TESTDRIVINGSMVISIBLELESS40_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM = {
   /* substruct: UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40') */
   {
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.proximity' (modeled as:'proximity.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.cruising' (modeled as:'cruising.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40') */
      true,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.green' (modeled as:'green.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40') */
      false,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.sm' (modeled as:'sm.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_TESTDRIVINGSMVISIBLELESS40_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40 = {
   /* substruct: UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40') */
   {
      /* type descriptor pointer 'driver_DrivingSM_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic_testDrivingSMVisibleLess40'
 * ----------------------------------------------------------------------------
 * model name:...................................'testDrivingSMVisibleLess40'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic_testDrivingSMVisibleLess40 (void)
{
   /* user defined local variables */
   boolean testGreen;
   float32 testProximity;

   testProximity = 30.0F;
   testGreen = false;
   _cov_statement_(170U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.cruising);
   _cov_statement_(171U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.proximity = testProximity;
   _cov_statement_(172U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.green = testGreen;
   _cov_statement_(173U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40.DrivingSM_testInstance));
   _cov_statement_(174U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40.DrivingSM_testInstance));
   _cov_statement_(175U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.cruising);
   _cov_statement_(176U);
   testGreen = true;
   _cov_statement_(177U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.green = testGreen;
   _cov_statement_(178U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40.DrivingSM_testInstance));
   _cov_statement_(179U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40.DrivingSM_testInstance));
   _cov_statement_(180U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_RAM.DrivingSM_testInstance.cruising);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleLess40_Automatic_testDrivingSMVisibleLess40'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



