/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_Light
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_Light_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_Light_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_Light'
 * data set:.....................................'UNITTESTS_UNITTEST_LIGHT_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_Light_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_Light_RAM = {
   /* struct element:'UnitTests_UnitTest_Light_RAM.elapsedTime' (modeled as:'elapsedTime.UnitTests_UnitTest_Light') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_Light_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_Light'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_Light_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_Light_Automatic_calc (/* IN    */ const float32 deltaT)
{
   _cov_statement_(98U);
   UnitTests_UnitTest_Light_RAM.elapsedTime = deltaT + UnitTests_UnitTest_Light_RAM.elapsedTime;
   _cov_statement_(99U);
   if (_cov_binary_branch_(0U, UnitTests_UnitTest_Light_RAM.elapsedTime >= 60.0F))
   {
      _cov_statement_(100U);
      UnitTests_UnitTest_Light_RAM.elapsedTime = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_Light_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_Light_Automatic_testTimer'
 * ----------------------------------------------------------------------------
 * model name:...................................'testTimer'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_Light_Automatic_testTimer (void)
{
   _cov_statement_(83U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 0.0, 0.001);
   _cov_statement_(84U);
   UnitTests_UnitTest_Light_Automatic_calc(5.0F);
   _cov_statement_(85U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 5.0, 0.001);
   _cov_statement_(86U);
   UnitTests_UnitTest_Light_Automatic_calc(30.0F);
   _cov_statement_(87U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 35.0, 0.001);
   _cov_statement_(88U);
   UnitTests_UnitTest_Light_Automatic_calc(20.0F);
   _cov_statement_(89U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 55.0, 0.001);
   _cov_statement_(90U);
   UnitTests_UnitTest_Light_Automatic_calc(4.0F);
   _cov_statement_(91U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 59.0, 0.001);
   _cov_statement_(92U);
   UnitTests_UnitTest_Light_Automatic_calc(1.0F);
   _cov_statement_(93U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 0.0, 0.001);
   _cov_statement_(94U);
   UnitTests_UnitTest_Light_Automatic_calc(60.0F);
   _cov_statement_(95U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 0.0, 0.001);
   _cov_statement_(96U);
   UnitTests_UnitTest_Light_Automatic_calc(45.0F);
   _cov_statement_(97U);
   ASSERT_NEAR((float64)UnitTests_UnitTest_Light_RAM.elapsedTime, 45.0, 0.001);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_Light_Automatic_testTimer'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



