/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_Light
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_UNITTESTS_UNITTEST_LIGHT_AUTOMATIC_H_
#define _ASD_UNITTESTS_UNITTEST_LIGHT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'UnitTests_UnitTest_Light_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_Light_Automatic_RAM_SUBSTRUCT {
   float32 elapsedTime;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'UnitTests_UnitTest_Light_Automatic'
 ******************************************************************************/


/* component structure for module UNITTESTS_UNITTEST_LIGHT_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........UnitTests_UnitTest_Light_Automatic */
#define _UnitTests_UnitTest_Light_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'UnitTests_UnitTest_Light_RAM' */
/* containing 'RAM' memory class tree */
extern struct UnitTests_UnitTest_Light_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_Light_RAM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module UnitTests_UnitTest_Light_Automatic
 ******************************************************************************/
extern void UnitTests_UnitTest_Light_Automatic_calc (/* IN    */ const float32 deltaT);
extern void UnitTests_UnitTest_Light_Automatic_testTimer (void);



#endif /* _ASD_UNITTESTS_UNITTEST_LIGHT_AUTOMATIC_H_ */
