/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................UnitTests.UnitTest_DrivingSM_testDrivingSMVisibleGreater40
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "coverageLib_CoverageInstrumentation_Automatic.h"
#include "StopRollGo_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_TESTDRIVINGSMVISIBLEGREATER40_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic_RAM_SUBSTRUCT UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM = {
   /* substruct: UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40') */
   {
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.proximity' (modeled as:'proximity.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40') */
      0.0F,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.cruising' (modeled as:'cruising.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40') */
      true,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.green' (modeled as:'green.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40') */
      false,
      /* struct element:'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.sm' (modeled as:'sm.DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40') */
      0U
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40'
 * data set:.....................................'UNITTESTS_UNITTEST_DRIVINGSM_TESTDRIVINGSMVISIBLEGREATER40_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40 = {
   /* substruct: UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40.DrivingSM_testInstance (modeled as:'DrivingSM_testInstance.UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40') */
   {
      /* type descriptor pointer 'driver_DrivingSM_Automatic_RAM' for memory class substruct for 'RAM' */
      &UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic_testDrivingSMVisibleGreater40'
 * ----------------------------------------------------------------------------
 * model name:...................................'testDrivingSMVisibleGreater40'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic_testDrivingSMVisibleGreater40 (void)
{
   /* user defined local variables */
   boolean testGreen;
   float32 testProximity;

   testProximity = 70.0F;
   testGreen = false;
   _cov_statement_(159U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.cruising);
   _cov_statement_(160U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.proximity = testProximity;
   _cov_statement_(161U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.green = testGreen;
   _cov_statement_(162U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40.DrivingSM_testInstance));
   _cov_statement_(163U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40.DrivingSM_testInstance));
   _cov_statement_(164U);
   ASSERT_FALSE(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.cruising);
   _cov_statement_(165U);
   testGreen = true;
   _cov_statement_(166U);
   UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.green = testGreen;
   _cov_statement_(167U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40.DrivingSM_testInstance));
   _cov_statement_(168U);
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(&(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40.DrivingSM_testInstance));
   _cov_statement_(169U);
   ASSERT_TRUE(UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_RAM.DrivingSM_testInstance.cruising);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'UnitTests_UnitTest_DrivingSM_testDrivingSMVisibleGreater40_Automatic_testDrivingSMVisibleGreater40'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



