/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................driver.driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_DRIVER_DRIVER_AUTOMATIC_PRIVATE
#define ESDL_DRIVER_DRIVER_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define DrivingSM_instance_VAL driver_driver.DrivingSM_instance
#define DrivingSM_instance_REF &(driver_driver.DrivingSM_instance)
#define InverseBrakeMomentum_VAL driver_driver_CAL_MEM.InverseBrakeMomentum
#define InverseBrakeMomentum_REF &(driver_driver_CAL_MEM.InverseBrakeMomentum)
#define requiredBrakeMomentum_VAL driver_driver_RAM.requiredBrakeMomentum
#define EdgeFalling_instance_VAL driver_driver.EdgeFalling_instance
#define EdgeFalling_instance_REF &(driver_driver.EdgeFalling_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_DRIVER_DRIVER_AUTOMATIC_PRIVATE */

