/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................driver.DrivingSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_DRIVER_DRIVINGSM_AUTOMATIC_PRIVATE
#define ESDL_DRIVER_DRIVINGSM_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define proximity_VAL self->driver_DrivingSM_Automatic_RAM->proximity
#define green_VAL self->driver_DrivingSM_Automatic_RAM->green
#define cruising_VAL self->driver_DrivingSM_Automatic_RAM->cruising
#define sm_VAL self->driver_DrivingSM_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_DRIVER_DRIVINGSM_AUTOMATIC_PRIVATE */

