/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................driver.DrivingSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "driver_DrivingSM_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define cruising_VAL (self->driver_DrivingSM_Automatic_RAM->cruising)
#define green_VAL (self->driver_DrivingSM_Automatic_RAM->green)
#define proximity_VAL (self->driver_DrivingSM_Automatic_RAM->proximity)
#define sm_VAL (self->driver_DrivingSM_Automatic_RAM->sm)

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define ACCState 0U
#define BrakeState 1U



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_drivingSMStatemachineTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'drivingSMStatemachineTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void driver_DrivingSM_Automatic_drivingSMStatemachineTrigger ( const struct driver_DrivingSM_Automatic * self)
{
   switch (sm_VAL)
   {
      case BrakeState:
         if (green_VAL)
         {
            sm_VAL = ACCState;
            break;
         } /* end if */
         cruising_VAL = false;
         break;
      case ACCState:
      default:
         if ((40.0F <= proximity_VAL) && (proximity_VAL <= 100.0F) && (!green_VAL))
         {
            sm_VAL = BrakeState;
            break;
         } /* end if */
         cruising_VAL = true;
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_drivingSMStatemachineTrigger'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_esdl_getState'
 * ----------------------------------------------------------------------------
 * model name:...................................'esdl_getState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 driver_DrivingSM_Automatic_esdl_getState ( const struct driver_DrivingSM_Automatic * self)
{
   return sm_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'driver_DrivingSM_Automatic_esdl_getState'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



