/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................driver.driver
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "driver_driver_Automatic.h"
#include "resources_CarMessages_Automatic.h"
#include "resources_TrafficLightMessages_Automatic.h"
#include "ESDL_Linear_Interpolation.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'driver_driver_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'driver_driver'
 * data set:.....................................'DRIVER_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct driver_driver_Automatic_CAL_MEM_SUBSTRUCT driver_driver_CAL_MEM = {
   /* struct element:'driver_driver_CAL_MEM.InverseBrakeMomentum' (modeled as:'InverseBrakeMomentum.driver_driver') */
   {
      5U,
      {
         -4.0F, -3.0F, -2.0F, -1.0F, 0.0F
      },
      {
         100.0F, 80.0F, 60.0F, 40.0F, 0.0F
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'driver_driver_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'driver_driver_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'driver_driver'
 * data set:.....................................'DRIVER_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct driver_driver_Automatic_RAM_SUBSTRUCT driver_driver_RAM = {
   /* struct element:'driver_driver_RAM.requiredBrakeMomentum' (modeled as:'requiredBrakeMomentum.driver_driver') */
   0.0F,
   /* substruct: driver_driver_RAM.DrivingSM_instance (modeled as:'DrivingSM_instance.driver_driver') */
   {
      /* struct element:'driver_driver_RAM.DrivingSM_instance.proximity' (modeled as:'proximity.DrivingSM_instance.driver_driver') */
      0.0F,
      /* struct element:'driver_driver_RAM.DrivingSM_instance.cruising' (modeled as:'cruising.DrivingSM_instance.driver_driver') */
      true,
      /* struct element:'driver_driver_RAM.DrivingSM_instance.green' (modeled as:'green.DrivingSM_instance.driver_driver') */
      false,
      /* struct element:'driver_driver_RAM.DrivingSM_instance.sm' (modeled as:'sm.DrivingSM_instance.driver_driver') */
      0U
   },
   /* substruct: driver_driver_RAM.EdgeFalling_instance (modeled as:'EdgeFalling_instance.driver_driver') */
   {
      /* struct element:'driver_driver_RAM.EdgeFalling_instance.buffer' (modeled as:'buffer.EdgeFalling_instance.driver_driver') */
      false,
      /* struct element:'driver_driver_RAM.EdgeFalling_instance.oldSignal' (modeled as:'oldSignal.EdgeFalling_instance.driver_driver') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'driver_driver_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'driver_driver'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'driver_driver'
 * data set:.....................................'DRIVER_DRIVER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct driver_driver_Automatic driver_driver = {
   /* substruct: driver_driver.DrivingSM_instance (modeled as:'DrivingSM_instance.driver_driver') */
   {
      /* type descriptor pointer 'driver_DrivingSM_Automatic_RAM' for memory class substruct for 'RAM' */
      &driver_driver_RAM.DrivingSM_instance
   },
   /* substruct: driver_driver.EdgeFalling_instance (modeled as:'EdgeFalling_instance.driver_driver') */
   {
      /* type descriptor pointer 'SystemLib_Miscellaneous_EdgeFalling_Impl_RAM' for memory class substruct for 'RAM' */
      &driver_driver_RAM.EdgeFalling_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'driver_driver'
 ******************************************************************************/





#define DrivingSM_instance_REF (&(driver_driver.DrivingSM_instance))
#define EdgeFalling_instance_REF (&(driver_driver.EdgeFalling_instance))
#define InverseBrakeMomentum_REF (&(driver_driver_CAL_MEM.InverseBrakeMomentum))
#define requiredBrakeMomentum_VAL (driver_driver_RAM.requiredBrakeMomentum)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'driver_driver_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void driver_driver_Automatic_calc (void)
{
   /* temp. variables */
   float32 _t1real32;
   uint32 _t1uint32;
   sint32 _t1sint32;

   /* define local message copies */
   float32 resources_CarMessages_brake__driver_driver_Automatic_calc;
   float32 resources_CarMessages_power__driver_driver_Automatic_calc;
   uint16 resources_CarMessages_v__driver_driver_Automatic_calc;
   boolean resources_TrafficLightMessages_green__driver_driver_Automatic_calc;
   float32 resources_TrafficLightMessages_visibleProximity__driver_driver_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_brake__driver_driver_Automatic_calc = resources_CarMessages_brake;
      resources_CarMessages_power__driver_driver_Automatic_calc = resources_CarMessages_power;
      resources_CarMessages_v__driver_driver_Automatic_calc = resources_CarMessages_v;
      resources_TrafficLightMessages_green__driver_driver_Automatic_calc = resources_TrafficLightMessages_green;
      resources_TrafficLightMessages_visibleProximity__driver_driver_Automatic_calc = resources_TrafficLightMessages_visibleProximity;
      EnableAllInterrupts();
   }
   driver_driver_RAM.DrivingSM_instance.proximity
      = resources_TrafficLightMessages_visibleProximity__driver_driver_Automatic_calc;
   driver_driver_RAM.DrivingSM_instance.green
      = resources_TrafficLightMessages_green__driver_driver_Automatic_calc;
   driver_DrivingSM_Automatic_drivingSMStatemachineTrigger(DrivingSM_instance_REF);
   SystemLib_Miscellaneous_EdgeFalling_Impl_compute(EdgeFalling_instance_REF, driver_driver_RAM.DrivingSM_instance.cruising);
   if (SystemLib_Miscellaneous_EdgeFalling_Impl_value(EdgeFalling_instance_REF))
   {
      _t1real32
         = (resources_TrafficLightMessages_visibleProximity__driver_driver_Automatic_calc + 8.0F) * 259200.0F;
      _t1uint32
         = (uint32)resources_CarMessages_v__driver_driver_Automatic_calc * resources_CarMessages_v__driver_driver_Automatic_calc;
      _t1sint32 = -(sint32)_t1uint32;
      requiredBrakeMomentum_VAL
         = ESDL_Linear_CharTable1_getAt_r32r32((InverseBrakeMomentum_REF)->xSize, (InverseBrakeMomentum_REF)->xDist, (InverseBrakeMomentum_REF)->values, ((_t1real32 == 0.0F) ? (float32)_t1sint32 : ((float32)_t1sint32 / _t1real32)));
   } /* end if */
   if (driver_driver_RAM.DrivingSM_instance.cruising)
   {
      if (resources_CarMessages_v__driver_driver_Automatic_calc >= 5000U)
      {
         resources_CarMessages_power__driver_driver_Automatic_calc = 0.0F;
         resources_CarMessages_brake__driver_driver_Automatic_calc = 70.0F;
      }
      else
      {
         resources_CarMessages_power__driver_driver_Automatic_calc = 100.0F;
         resources_CarMessages_brake__driver_driver_Automatic_calc = 0.0F;
      } /* end if */
   }
   else
   {
      resources_CarMessages_power__driver_driver_Automatic_calc = 0.0F;
      resources_CarMessages_brake__driver_driver_Automatic_calc = requiredBrakeMomentum_VAL;
   } /* end if */
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_brake = resources_CarMessages_brake__driver_driver_Automatic_calc;
      resources_CarMessages_power = resources_CarMessages_power__driver_driver_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'driver_driver_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



