/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLightController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_PRIVATE
#define ESDL_ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define TrafficLight_instance_VAL environment_TrafficLightController.TrafficLight_instance
#define TrafficLight_instance_REF &(environment_TrafficLightController.TrafficLight_instance)
#define TrafficLight_instance_2_VAL environment_TrafficLightController.TrafficLight_instance_2
#define TrafficLight_instance_2_REF &(environment_TrafficLightController.TrafficLight_instance_2)
#define TrafficLight_instance_3_VAL environment_TrafficLightController.TrafficLight_instance_3
#define TrafficLight_instance_3_REF &(environment_TrafficLightController.TrafficLight_instance_3)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_PRIVATE */

