/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLightController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "environment_TrafficLightController_Automatic.h"
#include "environment_FlashLight_Automatic.h"
#include "resources_CarMessages_Automatic.h"
#include "resources_TrafficLightMessages_Automatic.h"
#include "StopRollGoAPP_PC_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'environment_TrafficLightController_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'environment_TrafficLightController'
 * data set:.....................................'ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct environment_TrafficLightController_Automatic_RAM_SUBSTRUCT environment_TrafficLightController_RAM = {
   /* substruct: environment_TrafficLightController_RAM.TrafficLight_instance (modeled as:'TrafficLight_instance.environment_TrafficLightController') */
   {
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance.position' (modeled as:'position.TrafficLight_instance.environment_TrafficLightController') */
      0.0F,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance.proximity' (modeled as:'proximity.TrafficLight_instance.environment_TrafficLightController') */
      0.0F,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance.green' (modeled as:'green.TrafficLight_instance.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance.isVisible' (modeled as:'isVisible.TrafficLight_instance.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance.red' (modeled as:'red.TrafficLight_instance.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance.yellow' (modeled as:'yellow.TrafficLight_instance.environment_TrafficLightController') */
      false
   },
   /* substruct: environment_TrafficLightController_RAM.TrafficLight_instance_2 (modeled as:'TrafficLight_instance_2.environment_TrafficLightController') */
   {
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_2.position' (modeled as:'position.TrafficLight_instance_2.environment_TrafficLightController') */
      0.0F,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_2.proximity' (modeled as:'proximity.TrafficLight_instance_2.environment_TrafficLightController') */
      0.0F,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_2.green' (modeled as:'green.TrafficLight_instance_2.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_2.isVisible' (modeled as:'isVisible.TrafficLight_instance_2.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_2.red' (modeled as:'red.TrafficLight_instance_2.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_2.yellow' (modeled as:'yellow.TrafficLight_instance_2.environment_TrafficLightController') */
      false
   },
   /* substruct: environment_TrafficLightController_RAM.TrafficLight_instance_3 (modeled as:'TrafficLight_instance_3.environment_TrafficLightController') */
   {
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_3.position' (modeled as:'position.TrafficLight_instance_3.environment_TrafficLightController') */
      0.0F,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_3.proximity' (modeled as:'proximity.TrafficLight_instance_3.environment_TrafficLightController') */
      0.0F,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_3.green' (modeled as:'green.TrafficLight_instance_3.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_3.isVisible' (modeled as:'isVisible.TrafficLight_instance_3.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_3.red' (modeled as:'red.TrafficLight_instance_3.environment_TrafficLightController') */
      false,
      /* struct element:'environment_TrafficLightController_RAM.TrafficLight_instance_3.yellow' (modeled as:'yellow.TrafficLight_instance_3.environment_TrafficLightController') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'environment_TrafficLightController_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'environment_TrafficLightController'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'environment_TrafficLightController'
 * data set:.....................................'ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct environment_TrafficLightController_Automatic environment_TrafficLightController = {
   /* substruct: environment_TrafficLightController.TrafficLight_instance (modeled as:'TrafficLight_instance.environment_TrafficLightController') */
   {
      /* type descriptor pointer 'environment_TrafficLight_Automatic_RAM' for memory class substruct for 'RAM' */
      &environment_TrafficLightController_RAM.TrafficLight_instance
   },
   /* substruct: environment_TrafficLightController.TrafficLight_instance_2 (modeled as:'TrafficLight_instance_2.environment_TrafficLightController') */
   {
      /* type descriptor pointer 'environment_TrafficLight_Automatic_RAM' for memory class substruct for 'RAM' */
      &environment_TrafficLightController_RAM.TrafficLight_instance_2
   },
   /* substruct: environment_TrafficLightController.TrafficLight_instance_3 (modeled as:'TrafficLight_instance_3.environment_TrafficLightController') */
   {
      /* type descriptor pointer 'environment_TrafficLight_Automatic_RAM' for memory class substruct for 'RAM' */
      &environment_TrafficLightController_RAM.TrafficLight_instance_3
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'environment_TrafficLightController'
 ******************************************************************************/





#define TrafficLight_instance_2_REF (&(environment_TrafficLightController.TrafficLight_instance_2))
#define TrafficLight_instance_3_REF (&(environment_TrafficLightController.TrafficLight_instance_3))
#define TrafficLight_instance_REF (&(environment_TrafficLightController.TrafficLight_instance))


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'environment_TrafficLightController_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void environment_TrafficLightController_Automatic_calc (void)
{
   /* define local message copies */
   float32 resources_CarMessages_dist__environment_TrafficLightController_Automatic_calc;
   boolean resources_TrafficLightMessages_flashed__environment_TrafficLightController_Automatic_calc;
   boolean resources_TrafficLightMessages_green__environment_TrafficLightController_Automatic_calc;
   boolean resources_TrafficLightMessages_red__environment_TrafficLightController_Automatic_calc;
   float32 resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc;
   boolean resources_TrafficLightMessages_yellow__environment_TrafficLightController_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      resources_CarMessages_dist__environment_TrafficLightController_Automatic_calc = resources_CarMessages_dist;
      resources_TrafficLightMessages_flashed__environment_TrafficLightController_Automatic_calc = resources_TrafficLightMessages_flashed;
      resources_TrafficLightMessages_green__environment_TrafficLightController_Automatic_calc = resources_TrafficLightMessages_green;
      resources_TrafficLightMessages_red__environment_TrafficLightController_Automatic_calc = resources_TrafficLightMessages_red;
      resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc = resources_TrafficLightMessages_visibleProximity;
      resources_TrafficLightMessages_yellow__environment_TrafficLightController_Automatic_calc = resources_TrafficLightMessages_yellow;
      EnableAllInterrupts();
   }
   environment_TrafficLight_Automatic_setRed(TrafficLight_instance_REF, resources_TrafficLightMessages_red__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setRed(TrafficLight_instance_2_REF, resources_TrafficLightMessages_red__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setRed(TrafficLight_instance_3_REF, resources_TrafficLightMessages_red__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setYellow(TrafficLight_instance_REF, resources_TrafficLightMessages_yellow__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setYellow(TrafficLight_instance_2_REF, resources_TrafficLightMessages_yellow__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setYellow(TrafficLight_instance_3_REF, resources_TrafficLightMessages_yellow__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setGreen(TrafficLight_instance_REF, resources_TrafficLightMessages_green__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setGreen(TrafficLight_instance_2_REF, resources_TrafficLightMessages_green__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_setGreen(TrafficLight_instance_3_REF, resources_TrafficLightMessages_green__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_updateProximity(TrafficLight_instance_REF, resources_CarMessages_dist__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_updateProximity(TrafficLight_instance_2_REF, resources_CarMessages_dist__environment_TrafficLightController_Automatic_calc);
   environment_TrafficLight_Automatic_updateProximity(TrafficLight_instance_3_REF, resources_CarMessages_dist__environment_TrafficLightController_Automatic_calc);
   resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc = 0.0F;
   if (environment_TrafficLight_Automatic_getVisible(TrafficLight_instance_REF))
   {
      resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc
         = environment_TrafficLight_Automatic_getProximity(TrafficLight_instance_REF);
   } /* end if */
   if (environment_TrafficLight_Automatic_getVisible(TrafficLight_instance_2_REF))
   {
      resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc
         = environment_TrafficLight_Automatic_getProximity(TrafficLight_instance_2_REF);
   } /* end if */
   if (environment_TrafficLight_Automatic_getVisible(TrafficLight_instance_3_REF))
   {
      resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc
         = environment_TrafficLight_Automatic_getProximity(TrafficLight_instance_3_REF);
   } /* end if */
   resources_TrafficLightMessages_flashed__environment_TrafficLightController_Automatic_calc
      = environment_FlashLight_Automatic_calc(environment_TrafficLight_Automatic_getProximity(TrafficLight_instance_REF), environment_TrafficLight_Automatic_getProximity(TrafficLight_instance_2_REF), environment_TrafficLight_Automatic_getProximity(TrafficLight_instance_3_REF), resources_TrafficLightMessages_red__environment_TrafficLightController_Automatic_calc);
   /* send messages implicitly */
   {
      DisableAllInterrupts();
      resources_TrafficLightMessages_flashed = resources_TrafficLightMessages_flashed__environment_TrafficLightController_Automatic_calc;
      resources_TrafficLightMessages_visibleProximity = resources_TrafficLightMessages_visibleProximity__environment_TrafficLightController_Automatic_calc;
      EnableAllInterrupts();
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'environment_TrafficLightController_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'environment_TrafficLightController_Automatic_init'
 * ----------------------------------------------------------------------------
 * model name:...................................'init'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLightController_Automatic_init (void)
{
   environment_TrafficLight_Automatic_setPosition(TrafficLight_instance_REF, 300.0F);
   environment_TrafficLight_Automatic_setPosition(TrafficLight_instance_2_REF, 500.0F);
   environment_TrafficLight_Automatic_setPosition(TrafficLight_instance_3_REF, 900.0F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'environment_TrafficLightController_Automatic_init'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



