/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.LightSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_ENVIRONMENT_LIGHTSM_AUTOMATIC_PRIVATE
#define ESDL_ENVIRONMENT_LIGHTSM_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define elapsedTime_VAL self->environment_LightSM_Automatic_RAM->elapsedTime
#define red_VAL self->environment_LightSM_Automatic_RAM->red
#define yellow_VAL self->environment_LightSM_Automatic_RAM->yellow
#define green_VAL self->environment_LightSM_Automatic_RAM->green
#define sm_VAL self->environment_LightSM_Automatic_RAM->sm
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_ENVIRONMENT_LIGHTSM_AUTOMATIC_PRIVATE */

