/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLight
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "environment_TrafficLight_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define green_VAL (self->environment_TrafficLight_Automatic_RAM->green)
#define isVisible_VAL (self->environment_TrafficLight_Automatic_RAM->isVisible)
#define position_VAL (self->environment_TrafficLight_Automatic_RAM->position)
#define proximity_VAL (self->environment_TrafficLight_Automatic_RAM->proximity)
#define red_VAL (self->environment_TrafficLight_Automatic_RAM->red)
#define yellow_VAL (self->environment_TrafficLight_Automatic_RAM->yellow)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getGreen'
 * ----------------------------------------------------------------------------
 * model name:...................................'getGreen'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getGreen ( const struct environment_TrafficLight_Automatic * self)
{
   return green_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getGreen'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 environment_TrafficLight_Automatic_getPosition ( const struct environment_TrafficLight_Automatic * self)
{
   return position_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getProximity'
 * ----------------------------------------------------------------------------
 * model name:...................................'getProximity'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 environment_TrafficLight_Automatic_getProximity ( const struct environment_TrafficLight_Automatic * self)
{
   return proximity_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getProximity'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getRed'
 * ----------------------------------------------------------------------------
 * model name:...................................'getRed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getRed ( const struct environment_TrafficLight_Automatic * self)
{
   return red_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getRed'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getVisible'
 * ----------------------------------------------------------------------------
 * model name:...................................'getVisible'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getVisible ( const struct environment_TrafficLight_Automatic * self)
{
   return isVisible_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getVisible'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getYellow'
 * ----------------------------------------------------------------------------
 * model name:...................................'getYellow'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

boolean environment_TrafficLight_Automatic_getYellow ( const struct environment_TrafficLight_Automatic * self)
{
   return yellow_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_getYellow'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setGreen'
 * ----------------------------------------------------------------------------
 * model name:...................................'setGreen'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setGreen (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     g
   )
{
   green_VAL = g;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setGreen'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'setPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setPosition (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const float32                                     pos
   )
{
   position_VAL = pos;
   proximity_VAL = pos;
   environment_TrafficLight_Automatic_updateVisibility(self);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setRed'
 * ----------------------------------------------------------------------------
 * model name:...................................'setRed'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setRed (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     r
   )
{
   red_VAL = r;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setRed'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setYellow'
 * ----------------------------------------------------------------------------
 * model name:...................................'setYellow'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_setYellow (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     y
   )
{
   yellow_VAL = y;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_setYellow'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateProximity'
 * ----------------------------------------------------------------------------
 * model name:...................................'updateProximity'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_updateProximity (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const float32                                     carElapsed
   )
{
   proximity_VAL = position_VAL - carElapsed;
   environment_TrafficLight_Automatic_updateVisibility(self);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateProximity'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateVisibility'
 * ----------------------------------------------------------------------------
 * model name:...................................'updateVisibility'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_TrafficLight_Automatic_updateVisibility ( const struct environment_TrafficLight_Automatic * self)
{
   isVisible_VAL = (proximity_VAL >= 0.0F) && (proximity_VAL <= 100.0F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_TrafficLight_Automatic_updateVisibility'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



