/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.LightSM
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "environment_LightSM_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define elapsedTime_VAL (self->environment_LightSM_Automatic_RAM->elapsedTime)
#define green_VAL (self->environment_LightSM_Automatic_RAM->green)
#define red_VAL (self->environment_LightSM_Automatic_RAM->red)
#define sm_VAL (self->environment_LightSM_Automatic_RAM->sm)
#define yellow_VAL (self->environment_LightSM_Automatic_RAM->yellow)

/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define greenState 1U
#define redState 2U
#define yellowRedState 3U
#define yellowState 0U



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_LightSM_Automatic_esdl_getState'
 * ----------------------------------------------------------------------------
 * model name:...................................'esdl_getState'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 environment_LightSM_Automatic_esdl_getState ( const struct environment_LightSM_Automatic * self)
{
   return sm_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_LightSM_Automatic_esdl_getState'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'environment_LightSM_Automatic_trafficLightSMStatemachineTrigger'
 * ----------------------------------------------------------------------------
 * model name:...................................'trafficLightSMStatemachineTrigger'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void environment_LightSM_Automatic_trafficLightSMStatemachineTrigger ( const struct environment_LightSM_Automatic * self)
{
   switch (sm_VAL)
   {
      case greenState:
         if ((elapsedTime_VAL >= 0.0F) && (elapsedTime_VAL <= 44.0F))
         {
            sm_VAL = yellowState;
            break;
         } /* end if */
         red_VAL = false;
         yellow_VAL = false;
         green_VAL = true;
         break;
      case redState:
         if (elapsedTime_VAL >= 42.0F)
         {
            sm_VAL = yellowRedState;
            break;
         } /* end if */
         red_VAL = true;
         yellow_VAL = false;
         green_VAL = false;
         break;
      case yellowRedState:
         if (elapsedTime_VAL >= 44.0F)
         {
            sm_VAL = greenState;
            break;
         } /* end if */
         red_VAL = true;
         yellow_VAL = true;
         green_VAL = false;
         break;
      case yellowState:
      default:
         if (elapsedTime_VAL >= 3.0F)
         {
            sm_VAL = redState;
            break;
         } /* end if */
         red_VAL = false;
         yellow_VAL = true;
         green_VAL = false;
         break;
   } /* end switch */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'environment_LightSM_Automatic_trafficLightSMStatemachineTrigger'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



