/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.FlashLight
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_ENVIRONMENT_FLASHLIGHT_AUTOMATIC_H_
#define _ASD_ENVIRONMENT_FLASHLIGHT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/* component structure for module ENVIRONMENT_FLASHLIGHT_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........environment_FlashLight_Automatic */
#define _environment_FlashLight_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module environment_FlashLight_Automatic
 ******************************************************************************/
extern boolean environment_FlashLight_Automatic_calc (
   /* IN    */ const float32 proximity1,
   /* IN    */ const float32 proximity2,
   /* IN    */ const float32 proximity3,
   /* IN    */ const boolean isRed
   );



#endif /* _ASD_ENVIRONMENT_FLASHLIGHT_AUTOMATIC_H_ */
