/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLight
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_ENVIRONMENT_TRAFFICLIGHT_AUTOMATIC_H_
#define _ASD_ENVIRONMENT_TRAFFICLIGHT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'environment_TrafficLight_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct environment_TrafficLight_Automatic_RAM_SUBSTRUCT {
   float32 position;
   float32 proximity;
   boolean green;
   boolean isVisible;
   boolean red;
   boolean yellow;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'environment_TrafficLight_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'environment_TrafficLight_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct environment_TrafficLight_Automatic {
   struct environment_TrafficLight_Automatic_RAM_SUBSTRUCT * environment_TrafficLight_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'environment_TrafficLight_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........environment_TrafficLight_Automatic */
#define _environment_TrafficLight_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class environment_TrafficLight_Automatic
 ******************************************************************************/
extern boolean environment_TrafficLight_Automatic_getGreen ( const struct environment_TrafficLight_Automatic * self);
extern float32 environment_TrafficLight_Automatic_getPosition ( const struct environment_TrafficLight_Automatic * self);
extern float32 environment_TrafficLight_Automatic_getProximity ( const struct environment_TrafficLight_Automatic * self);
extern boolean environment_TrafficLight_Automatic_getRed ( const struct environment_TrafficLight_Automatic * self);
extern boolean environment_TrafficLight_Automatic_getVisible ( const struct environment_TrafficLight_Automatic * self);
extern boolean environment_TrafficLight_Automatic_getYellow ( const struct environment_TrafficLight_Automatic * self);
extern void environment_TrafficLight_Automatic_setGreen (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     g
   );
extern void environment_TrafficLight_Automatic_setPosition (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const float32                                     pos
   );
extern void environment_TrafficLight_Automatic_setRed (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     r
   );
extern void environment_TrafficLight_Automatic_setYellow (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const boolean                                     y
   );
extern void environment_TrafficLight_Automatic_updateProximity (
               const struct environment_TrafficLight_Automatic * self,
   /* IN    */ const float32                                     carElapsed
   );
void environment_TrafficLight_Automatic_updateVisibility ( const struct environment_TrafficLight_Automatic * self);



#endif /* _ASD_ENVIRONMENT_TRAFFICLIGHT_AUTOMATIC_H_ */
