/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.Light
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_ENVIRONMENT_LIGHT_AUTOMATIC_PRIVATE
#define ESDL_ENVIRONMENT_LIGHT_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define elapsedTime_VAL environment_Light_RAM.elapsedTime
#define TrafficLightSM_instance_VAL environment_Light.TrafficLightSM_instance
#define TrafficLightSM_instance_REF &(environment_Light.TrafficLightSM_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_ENVIRONMENT_LIGHT_AUTOMATIC_PRIVATE */

