/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLightController
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_H_
#define _ASD_ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "environment_TrafficLight_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'environment_TrafficLightController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct environment_TrafficLightController_Automatic_RAM_SUBSTRUCT {
   struct environment_TrafficLight_Automatic_RAM_SUBSTRUCT TrafficLight_instance;
   struct environment_TrafficLight_Automatic_RAM_SUBSTRUCT TrafficLight_instance_2;
   struct environment_TrafficLight_Automatic_RAM_SUBSTRUCT TrafficLight_instance_3;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'environment_TrafficLightController_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'environment_TrafficLightController_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct environment_TrafficLightController_Automatic {
   struct environment_TrafficLight_Automatic TrafficLight_instance;
   struct environment_TrafficLight_Automatic TrafficLight_instance_2;
   struct environment_TrafficLight_Automatic TrafficLight_instance_3;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'environment_TrafficLightController_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: environment_TrafficLightController_Automatic */
#define _environment_TrafficLightController_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'environment_TrafficLightController_RAM' */
/* containing 'RAM' memory class tree */
extern struct environment_TrafficLightController_Automatic_RAM_SUBSTRUCT environment_TrafficLightController_RAM;

/* forward declaration of component variable 'environment_TrafficLightController' */
/* containing 'ROM' memory class tree */
extern const struct environment_TrafficLightController_Automatic environment_TrafficLightController;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module environment_TrafficLightController_Automatic
 ******************************************************************************/
extern void environment_TrafficLightController_Automatic_calc (void);
extern void environment_TrafficLightController_Automatic_init (void);



#endif /* _ASD_ENVIRONMENT_TRAFFICLIGHTCONTROLLER_AUTOMATIC_H_ */
