/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.Light
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_ENVIRONMENT_LIGHT_AUTOMATIC_H_
#define _ASD_ENVIRONMENT_LIGHT_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "environment_LightSM_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'environment_Light_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct environment_Light_Automatic_RAM_SUBSTRUCT {
   float32 elapsedTime;
   struct environment_LightSM_Automatic_RAM_SUBSTRUCT TrafficLightSM_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'environment_Light_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'environment_Light_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct environment_Light_Automatic {
   struct environment_LightSM_Automatic TrafficLightSM_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'environment_Light_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ................environment_Light_Automatic */
#define _environment_Light_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'environment_Light_RAM' */
/* containing 'RAM' memory class tree */
extern struct environment_Light_Automatic_RAM_SUBSTRUCT environment_Light_RAM;

/* forward declaration of component variable 'environment_Light' */
/* containing 'ROM' memory class tree */
extern const struct environment_Light_Automatic environment_Light;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module environment_Light_Automatic
 ******************************************************************************/
extern void environment_Light_Automatic_calc (void);



#endif /* _ASD_ENVIRONMENT_LIGHT_AUTOMATIC_H_ */
