/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................environment.TrafficLight
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_ENVIRONMENT_TRAFFICLIGHT_AUTOMATIC_PRIVATE
#define ESDL_ENVIRONMENT_TRAFFICLIGHT_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define red_VAL self->environment_TrafficLight_Automatic_RAM->red
#define yellow_VAL self->environment_TrafficLight_Automatic_RAM->yellow
#define green_VAL self->environment_TrafficLight_Automatic_RAM->green
#define isVisible_VAL self->environment_TrafficLight_Automatic_RAM->isVisible
#define proximity_VAL self->environment_TrafficLight_Automatic_RAM->proximity
#define position_VAL self->environment_TrafficLight_Automatic_RAM->position
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_ENVIRONMENT_TRAFFICLIGHT_AUTOMATIC_PRIVATE */

