/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................resources.TrafficLightMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    
 ******************************************************************************/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "resources_TrafficLightMessages_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'resources_TrafficLightMessages'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................8
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'resources_TrafficLightMessages_visibleProximity' */
float32 resources_TrafficLightMessages_visibleProximity = 0.0F;
/* messages of size [bytes]:................................................1 */
/* modelled as 'resources_TrafficLightMessages_flashed' */
boolean resources_TrafficLightMessages_flashed = false;
/* modelled as 'resources_TrafficLightMessages_green' */
boolean resources_TrafficLightMessages_green = false;
/* modelled as 'resources_TrafficLightMessages_red' */
boolean resources_TrafficLightMessages_red = false;
/* modelled as 'resources_TrafficLightMessages_yellow' */
boolean resources_TrafficLightMessages_yellow = false;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



