/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................resources.TrafficLightMessages
 * REPRESENTATION:..............Automatic
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_RESOURCES_TRAFFICLIGHTMESSAGES_AUTOMATIC_PRIVATE
#define ESDL_RESOURCES_TRAFFICLIGHTMESSAGES_AUTOMATIC_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define resources_TrafficLightMessages_red_VAL resources_TrafficLightMessages_red
#define resources_TrafficLightMessages_yellow_VAL resources_TrafficLightMessages_yellow
#define resources_TrafficLightMessages_green_VAL resources_TrafficLightMessages_green
#define resources_TrafficLightMessages_flashed_VAL resources_TrafficLightMessages_flashed
#define resources_TrafficLightMessages_visibleProximity_VAL resources_TrafficLightMessages_visibleProximity
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_RESOURCES_TRAFFICLIGHTMESSAGES_AUTOMATIC_PRIVATE */

