/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................StopRollGoAPP_PC
 * REPRESENTATION:..............
 * DESCRIPTION:
 *    
 ******************************************************************************/
#ifndef _ASD_STOPROLLGOAPP_PC_AUTOMATIC_H_
#define _ASD_STOPROLLGOAPP_PC_AUTOMATIC_H_


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#if (!defined(ESDL_HEADER_VERSION) || (ESDL_HEADER_VERSION < 5))
# error NOT COMPLIANT (< compliance level 5) VERSION OF esdl.h FOUND; To fix that, delete the old headers (esdl_<...>.h) in include folder and restart build again to get the new version of those files.
#endif
#include "chartab.h"
#include "driver_driver_Automatic.h"
#include "environment_FlashLight_Automatic.h"
#include "environment_Light_Automatic.h"
#include "environment_TrafficLightController_Automatic.h"
#include "myCar_myCar_Automatic.h"
#include "myCar_TimeBase_Automatic.h"
#include "resources_CarMessages_Automatic.h"
#include "resources_TrafficLightMessages_Automatic.h"


/* component structure for project STOPROLLGOAPP_PC_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .................StopRollGoAPP_PC_Automatic */
#define _StopRollGoAPP_PC_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project StopRollGoAPP_PC_Automatic
 ******************************************************************************/



#endif /* _ASD_STOPROLLGOAPP_PC_AUTOMATIC_H_ */
