/******************************************************************************
 * DO NOT EDIT!
 * AUTOMATICALLY GENERATED BY:..ASCET-DEVELOPER V7.7.0
 * CODE GENERATOR:..............V7.7.0
 * COMPONENT:...................SystemLib.Miscellaneous.EdgeFalling
 * REPRESENTATION:..............Impl
 * DESCRIPTION:
 *    Private access macros
 ******************************************************************************/
#ifndef ESDL_SYSTEMLIB_MISCELLANEOUS_EDGEFALLING_IMPL_PRIVATE
#define ESDL_SYSTEMLIB_MISCELLANEOUS_EDGEFALLING_IMPL_PRIVATE

/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define buffer_VAL self->SystemLib_Miscellaneous_EdgeFalling_Impl_RAM->buffer
#define oldSignal_VAL self->SystemLib_Miscellaneous_EdgeFalling_Impl_RAM->oldSignal
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* ESDL_SYSTEMLIB_MISCELLANEOUS_EDGEFALLING_IMPL_PRIVATE */

